"""Selected channel adaptation, shared replay only; private trials are disabled.

Source: QuantConnect Documentation, Apache-2.0,
a0fcde52f4a9acd88fb3720ff7aaff1e3f2be1be,
project-templates/python/equity-donchian-breakout-turtle/main.py.
Independently written adaptation: hourly rolling 480/240, fixed cash budget,
prior-window close decision / next open. No equity session or ATR sizing.
"""
from tidelab.batch_review import review_scenarios
from tidelab.strategy_intake import record_digest

CANDIDATE = "qc-channel-breakout-480-240-long-cash"
REVIEW_POLICY = "channel-breakout-v1-five-round-trips"


def package(record: dict) -> dict:
    if record["source"]["kind"] != "synthetic_example" and record["candidate_id"] != CANDIDATE:
        raise ValueError("outside_selected_channel_candidate")
    return {"schema_version": 3, "strategy_id": CANDIDATE, "version": 1,
        "source": {"candidate_id": record["candidate_id"], "version": record["version"],
                   "record_sha256": record_digest(record)},
        "requirements": {"interval_seconds": 3600, "product_class": "spot", "position_mode": "long_cash"},
        "rule": {"entry": {"op": "gt", "left": {"op": "close", "lag": 0},
                           "right": {"op": "donchian_upper", "window": 480, "lag": 1}},
                 "exit": {"op": "lt", "left": {"op": "close", "lag": 0},
                          "right": {"op": "donchian_lower", "window": 240, "lag": 1}},
                 "target_fraction": "0.25"}}


class UnapprovedChannelPolicy:
    """Hard stop before store, snapshot or source access; there is no grant flag.

    A future owner-approved trial needs a separately reviewed admission change.
    An implementation-selected record, renamed file or fabricated receipt cannot
    enable this policy. The synthetic route uses ordinary historical_batch.run.
    """
    @staticmethod
    def preflight(*args, **kwargs):
        raise ValueError("channel_trial_authority_ungranted")

    package = preflight
    read_partition = preflight


def prepare_private(*args, **kwargs):
    UnapprovedChannelPolicy.preflight()


def execute_private(*args, **kwargs):
    UnapprovedChannelPolicy.preflight()


def review(summary: dict, market_order: list[str]) -> dict:
    # Until trial authority exists, report only synthetic demonstration outcomes.
    if summary.get("kind") != "synthetic":
        raise ValueError("channel_trial_authority_ungranted")
    result = review_scenarios(summary, market_order, minimum_round_trips=5,
                              scope="descriptive_synthetic_triage_not_research_evidence")
    result["policy"] = REVIEW_POLICY
    return result


def review_artifacts(output):
    """Verify a retained synthetic batch before deriving descriptive diagnostics."""
    from decimal import Decimal
    from tidelab import historical_batch as batch
    from tidelab.batch_review import trace_diagnostics
    batch.verify(output)
    batch.verify(output / "inputs")
    plan = batch.read(output / "inputs/plan.json")
    descriptor = batch.read(output / "inputs/snapshot.json")
    batch.preflight(plan, descriptor)
    refs = plan["packages"]
    if len(refs) != 1:
        raise ValueError("outside_channel_inventory")
    # Frozen filenames are generated by the shared backend, not caller paths.
    record = batch.read(output / "inputs/record-0.json")
    candidate = batch.read(output / "inputs/package-0.json")
    if candidate != package(record):
        raise ValueError("outside_selected_channel_candidate")
    expected = [{"package": refs[0]["id"], "market": m, "cost": c, "benchmark": b}
                for m in plan["markets"] for b in (None, "cash", "passive") for c in ("baseline", "stress")]
    if plan["jobs"] != expected or len(plan["markets"]) != 5:
        raise ValueError("outside_channel_inventory")
    summary = batch.read(output / "summary.json")
    result = review({**summary, "kind": "synthetic"}, plan["markets"])
    diagnostics = []
    for row in summary["jobs"]:
        if row["status"] != "completed":
            continue
        index = row["index"]
        cost = plan["costs"][expected[index]["cost"]]
        diagnostics.append({"index": index, **trace_diagnostics(output / f"job-{index}" / "trace.jsonl",
            fee_rate=Decimal(cost["fee_rate"]), adverse_rate=Decimal(cost["adverse_rate"]))})
    result["diagnostics"] = diagnostics
    return result
